spring:
  application:
    name: server-gateway
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:31642
      config:
        server-addr: 127.0.0.1:31642
        file-extension: yaml
  config:
    import:
      - nacos:common.yaml
      - nacos:${spring.application.name}-${spring.profiles.active}.yaml